#!/usr/bin/env bash

printf "\n-----------------\nConfiguring Files\n-----------------\n"

# Install the Friendly Interactive SHell
sudo apt install fish
chsh -s /usr/bin/fish

# Apache Webserver Setup
echo "Would you like to set up a web server? (y/n)"
read $webserver

if [ $webserver = "n" ] then
  echo "we didn't set that up for ya"
fi







exec fish
