#!/bin/bash

  # INSTALL THE DOTFILES

        # Here's a list:
            # Fish 
            # VIM
            # neomutt
      # unzip       # ranger
      # lynx        # nodejs
      # perl6       # golang
      # wget        # cointop
      # make        # markdown-pdf 
      # gcc         # apache2
      # php         # certbot
      # python2+3   # mysql


echo ""
echo "Installing Dotfiles"
echo ""

# All the 'apt install's 
# and 'snap install's
  sudo apt  install   unzip ranger lynx \
                      nodejs perl6 golang \
                      wget make markdown-pdf \
                      gcc apache2 certbot mysql \
                      python3 python php \
                      neomutt vim fish 
  sudo snap install   cointop

# Set System GMT
  sudo timedatectl set-timezone Europe/London

  cd ${HOME}
# Creating Folder Structure
  if [ ! -d ".config" ]
  # .config Folder
    mkdir .config
    cd .config
  elif [ ! -d "fish" ]
  # FISh Folder
    mkdir fish
  elif [ ! -d "no-more-secrets" ]
  # NMS Folder
    git clone https://github.com/bartobri/no-more-secrets.git
    cd ./no-more-secrets
    make nms
    sudo make install
    cd ..
  elif [ ! -d "ranger" ]
  # Ranger Folder
    mkdir ranger
  elif [ ! -d "mutt" ]
  # Mutt Folder
    mkdir mutt
  else 
    echo "Done with folder .config"
  fi

# End of Install: Auto Remove
  echo ""
  echo "Everything's done! Autoremove is now possible:"
  sudo apt autoremove
  cd ~/dotfiles
# exec fish


# VIMSTALL from 
#   https://github.com/OfficialKingJulian/vim
    cd ${HOME}/
    mkdir tempvim
    cd tempvim
    git clone https://github.com/OfficialKingJulian/vim
  # Run Installation File
    ${HOME}/tempvim/vim/vimstall
  # Remove Supporting Files
    sudo rm -r ${HOME}/tempvim
    echo ""
    echo "vim should be successfully installed"





