#!/bin/bash


echo ""
echo "Installing Dotfiles"
echo ""

# All the 'apt install's 
# and 'snap install's
  sudo apt  remove   unzip ranger lynx \
                     nodejs perl6 golang \
                     wget make markdown-pdf \
                     gcc apache2 certbot mysql \
                     python3 python php \
                     neomutt vim fish 
  sudo snap remove   cointop

# Remove Folder Setup
  cd ${HOME}
  sudo rm -r .config

# VIMuninstall
  sudo rm -r ${HOME}/.config/vim  
  sudo rm -r ${HOME}/.vim


