#!/bin/bash

# Title:	pwdmgr
# By: 		OfficialKingJulian
# Tag Added:	02-02-2020
# Description:  Simple GPG encrypted password storage in a local folder

if [[ ! -z ${1} ]] ; then
  name=${1}
  pass=${2}
else
  printf "Enter the account username/name you want to store: "
  read -r name
  printf "Enter the password (should not display whilst typing): "
  read -sr pass
fi
echo "${pass}" > "${HOME}/passwds/${name}"
gpg -r contact@julians.email -e "${HOME}/passwds/${name}"
shred "${HOME}/passwds/${name}"
rm "${HOME}/passwds/${name}"
