#!/bin/bash

# Get a random background
# based on the current month

  currmon=$(date +%b | awk '{print tolower($0)}')
  echo $currmon

  img=$(find "${HOME}/Pictures/Wallpapers/months/${currmon}/" -type f | shuf -n 1)
  i3lock -i $img
