#!/bin/sh

sxhkd &

# General
  bspc monitor -d     
  bspc config border_width         1
  bspc config window_gap           20
  bspc config split_ratio          0.52
  bspc config borderless_monocle   true
  bspc config gapless_monocle      true

# Window Rules
# bspc rule -a Gimp desktop='^8' state=floating follow=on
  bspc rule -a Firefox desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Run These Please
# Polybar
  /home/julian/.config/bspwm/bin/poly &
# Compton
  pkill compton &
  compton -b &
# Background
  pkill bg &
  /home/julian/.config/bspwm/bin/bg &

