#!/bin/bash

# a very basic script
# to get new ad blocker 
# hosts file 

  hosts="http://winhelp2002.mvps.org/hosts.txt"
  if [ -z "$(curl -I "${hosts}" 2>&1 | grep '200 OK' )" ]; then exit 0; fi
  wget -O - "${hosts}" > /etc/hosts
