#!/bin/bash

# Only deals with folder names without 
# spaces. Also only goes to one level
# of folder depth; this was all I needed
# so didn't add any further depth.

# Writes to the File 
  writeToFile() {
    printf "macro index,pager \cm\c${Shortcut} \"<copy-message>?c"  >> $Outputfile
  # Backspace x42 
    for i in {1..42} ; do
      printf "<backspace>" >> $Outputfile
    done
    printf "imaps://imap-mail.outlook.com:993/${Folder}<enter><enter>ydd\" \"Move Item to \'${Folder}\'. Added Automatically by MuttIndexer \"" >> $Outputfile
    echo "" >> $Outputfile
  }

# Specify the Output file and Find the Mailbox(es - further dev)
  cd ~/.mutt
  inboxLocations=(`find / -xdev 2>/dev/null -name "Inbox"`)

  # Title 
    echo ""
    echo Automatically create shortcuts to move mail between folders in neomutt! \(Only working with Outlook, currently\)
    echo ""

# Loop Through All Mailboxes
  counter=0
  for InboxLocation in "${inboxLocations[@]}"; do

  # Get Mailbox
    cd $InboxLocation
    cd ..
    # We're  at  the 
    # right location

  # Specify Output File - NOT THIS SIMPLE
    counter=${counter}+1
    Outputfile="${HOME}/.mutt/bindings-acct-${counter}.mutt"
   
  # Test For Multiple Mailboxes
    if [ ${#inboxLocations[@]}>1 ] ; then 
      echo "Multiple Mailboxes Found: "
    else
      echo "One mailbox; this should be easy!"
    fi
    echo $PWD
    echo ""

  # Loop through folder
    for folder in * ; do

      if [ -d ${folder} ]; then

        echo Assign a shortcut to ${folder} - leave blank to skip
        read Shortcut
        if [ -z $Shortcut ] ; then 
        # Skip
          echo Skip 
          echo ""
        else 
        # Call Write To File
          Folder=${folder}
          writeToFile
        fi

        # cd into nested folder
        cd $folder 
        for folder2 in * ; do

          if [ -d ${folder2} ] ; then
            echo Assign a shortcut to ${folder}/${folder2} - leave blank to skip
            read Shortcut
            if [ -z $Shortcut ] ; then 
            # Skip
              echo Skip 
              echo ""
            else 
            # Call Write To File
              Folder=${folder}/${folder2}
              writeToFile
            fi
          fi

        done
        cd ..
        # cd back out

      fi

    done

  done


