#!/usr/bin/env fish

# https://github.com/fish-shell/fish-shell/issues/2639
# This took too long to find an answer to... 

function fish_prompt
  echo "prompt"
end

echo $fish_user_paths | tr " " "\n" | nl

echo "Which one would you like to remove?"
New Prompt %

if test $toremove = 1 
  echo "bloop"
end
