#!/bin/bash

# Just makes 'whois' slightly more flexible.
# Not sure why it doesn't do this as standard
# but I'm sure I'll find out when it does wrong
  newis=$(echo "${1}" | sed -E "s/(https:\/\/)|(http:\/\/)//g")
  newis=$(echo "$newis" | sed -E "s/(\/.*)//g")
  whois "$newis"
